In [1]:
import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
np.shape(a)

(3,)

In [4]:
a[1]

2

# Matrices

In [5]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [6]:
b.shape

(3, 3)

In [8]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
d = np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
g = b[1:,1:] # row_start:row_end , column_start:column_end
g

array([[5, 6],
       [8, 9]])

In [13]:
g[1,1] = 2021
g

array([[   5,    6],
       [   8, 2021]])

In [14]:
b

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 2021]])

In [16]:
b[1,1] = 45
b

array([[   1,    2,    3],
       [   4,   45,    6],
       [   7,    8, 2021]])

In [17]:
g

array([[  45,    6],
       [   8, 2021]])

In [20]:
x = np.array([
    [1,2],
    [3,4]
],
dtype = np.float64)

y = np.array([
    [5,6],
    [7,8]
],
dtype = np.float64)

print('El matriz x es: \n',x)
print('El matriz y es: \n',y)

El matriz x es: 
 [[1. 2.]
 [3. 4.]]
El matriz y es: 
 [[5. 6.]
 [7. 8.]]


In [21]:
print(np.array_equal(x+y, np.add(x,y)))

True


In [22]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [23]:
print(np.array_equal(x-y,np.subtract(x,y)))

True


In [24]:
print(np.array_equal(x*y,np.multiply(x,y)))

True


In [25]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [26]:
np.sum(x, axis=1)#axis 1 = rows

array([3., 7.])

In [27]:
x

array([[1., 2.],
       [3., 4.]])

In [28]:
np.sum(x, axis=0) #axis 0 = columns

array([4., 6.])