Introducción

In [1]:
print('hola')

hola


In [2]:
nombre = 'My name '
print(nombre)

My name 


In [3]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [4]:
%pwd

'/home/jovyan'

In [5]:
%ls

 00_00_binder.ipynb                    'Clase 1 - Basicos.ipynb'
 00_00_primer_pasos.ipynb               datasets/
 01_01_data_types.ipynb                 README.md
 01_02_read_iloc_unique_groupby.ipynb   _read_me.txt
 01_03_data_wrangling.ipynb             requirements.txt


In [7]:
import numpy as np
n = 50
numeros_random = np.random.rand(n)
numeros_random

array([0.52503053, 0.43067778, 0.56626019, 0.79819244, 0.1339645 ,
       0.97892563, 0.69330988, 0.62680395, 0.0706253 , 0.74736093,
       0.66602316, 0.95431042, 0.91632169, 0.75961322, 0.27074103,
       0.94685153, 0.85069879, 0.24537786, 0.71012981, 0.0666395 ,
       0.21594816, 0.53677436, 0.47109795, 0.90696762, 0.6932403 ,
       0.03563493, 0.7702433 , 0.13276624, 0.84621502, 0.4508629 ,
       0.78157771, 0.94561121, 0.48477801, 0.68140493, 0.09153658,
       0.20194447, 0.86765715, 0.84584324, 0.12958988, 0.35877486,
       0.22261156, 0.73102476, 0.2749439 , 0.56366344, 0.39172957,
       0.14559908, 0.9363969 , 0.02828535, 0.7207005 , 0.35787264])

In [8]:
import math
type(4)

int

In [9]:
type(4.2)

float

In [10]:
type('my name')

str

In [11]:
type(True)

bool

In [12]:
type(2/5)

float

In [13]:
type(None)

NoneType

In [14]:
an_array = [1, 2, 3, 4, 10]

In [15]:
print(an_array)

[1, 2, 3, 4, 10]


In [17]:
suma_array = sum(an_array)

In [18]:
mean_an_array = suma_array/len(an_array)

In [19]:
mean_an_array

4.0

In [20]:
len(an_array)

5

In [21]:
6*10**2

600

In [22]:
6*10**(-1)

0.6000000000000001

In [23]:
math.pi

3.141592653589793

In [24]:
otra_array = [2, math.pi, 3/5, 'a_str']
otra_array

[2, 3.141592653589793, 0.6, 'a_str']

In [28]:
x = 6
y = 8

if x<7 :
    print('{} es menor que {}'.format(x,y))
else:
    print('{} es menor que {}'.format(y,x))

6 es menor que 8


In [29]:
my_List = [True, 6<5, 1==3, None is None]
my_List

[True, False, False, True]

In [31]:
for i in my_List:
    print('{}\t {}'.format(i, type(i)))

True	 <class 'bool'>
False	 <class 'bool'>
False	 <class 'bool'>
True	 <class 'bool'>


In [32]:
x = None
type(x)

NoneType

In [36]:
none_list = [None]*5
none_list

[None, None, None, None, None]

In [37]:
len(none_list)

5

In [38]:
una_lista = ['pos_0', 'first', 'second', 'third', 'forth', 'fifth']
una_lista

['pos_0', 'first', 'second', 'third', 'forth', 'fifth']

In [50]:
una_lista

['pos_0', 'first', 'second', 'third', 'forth', 'fifth']

In [68]:
una_lista.sort()
una_lista

['fifth', 'first', 'forth', 'pos_0', 'second', 'third']

In [51]:
una_lista[:]

['pos_0', 'first', 'second', 'third', 'forth', 'fifth']

In [39]:
len(una_lista)

6

In [40]:
una_lista[2]

'second'

In [41]:
una_lista[0:4]

['pos_0', 'first', 'second', 'third']

In [42]:
una_lista[:4]

['pos_0', 'first', 'second', 'third']

In [43]:
una_lista[1:4]

['first', 'second', 'third']

In [47]:
una_lista[-2:]

['forth', 'fifth']

In [48]:
una_lista[-1]

'fifth'

In [49]:
una_lista[-4:-1]

['second', 'third', 'forth']

In [55]:
num_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
num_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
type(num_array)

numpy.ndarray

In [56]:
np.mean(num_array)

5.0

In [58]:
sum(num_array)/len(num_array)

5.0

In [59]:
np.dot(3,4)

12

In [63]:
np.dot([2j, 3j], [2j, 3j])


(-13+0j)

In [64]:
import pandas as pd

data_set = 'datasets/Cartwheeldata.csv'
df = pd.read_csv(data_set)

In [65]:
df

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0    1   56      F            1       Y             1   62.00      61.0   
1    2   26      F            1       Y             1   62.00      60.0   
2    3   33      F            1       Y             1   66.00      64.0   
3    4   39      F            1       N             0   64.00      63.0   
4    5   27      M            2       N             0   73.00      75.0   
5    6   24      M            2       N             0   75.00      71.0   
6    7   28      M            2       N             0   75.00      76.0   
7    8   22      F            1       N             0   65.00      62.0   
8    9   29      M            2       Y             1   74.00      73.0   
9   10   33      F            1       Y             1   63.00      60.0   
10  11   30      M            2       Y             1   69.50      66.0   
11  12   28      F            1       Y             1   62.75      58.0   
12  13   25      F            1       Y             1   65.00      64.5   
13  14   23      F            1       N             0   61.50      57.5   
14  15   31      M            2       Y             1   73.00      74.0   
15  16   26      M            2       Y             1   71.00      72.0   
16  17   26      F            1       N             0   61.50      59.5   
17  18   27      M            2       N             0   66.00      66.0   
18  19   23      M            2       Y             1   70.00      69.0   
19  20   24      F            1       Y             1   68.00      66.0   
20  21   23      M            2       Y             1   69.00      67.0   
21  22   29      M            2       N             0   71.00      70.0   
22  23   25      M            2       N             0   70.00      68.0   
23  24   26      M            2       N             0   69.00      71.0   
24  25   23      F            1       Y             1   65.00      63.0   

    CWDistance Complete  CompleteGroup  Score  
0           79        Y              1      7  
1           70        Y              1      8  
2           85        Y              1      7  
3           87        Y              1     10  
4           72        N              0      4  
5           81        N              0      3  
6          107        Y              1     10  
7           98        Y              1      9  
8          106        N              0      5  
9           65        Y              1      8  
10          96        Y              1      6  
11          79        Y              1     10  
12          92        Y              1      6  
13          66        Y              1      4  
14          72        Y              1      9  
15         115        Y              1      6  
16          90        N              0     10  
17          74        Y              1      5  
18          64        Y              1      3  
19          85        Y              1      8  
20          66        N              0      2  
21         101        Y              1      8  
22          82        Y              1      4  
23          63        Y              1      5  
24          67        N              0      3

In [66]:
df.head(13)

ID  Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0    1   56      F            1       Y             1   62.00      61.0   
1    2   26      F            1       Y             1   62.00      60.0   
2    3   33      F            1       Y             1   66.00      64.0   
3    4   39      F            1       N             0   64.00      63.0   
4    5   27      M            2       N             0   73.00      75.0   
5    6   24      M            2       N             0   75.00      71.0   
6    7   28      M            2       N             0   75.00      76.0   
7    8   22      F            1       N             0   65.00      62.0   
8    9   29      M            2       Y             1   74.00      73.0   
9   10   33      F            1       Y             1   63.00      60.0   
10  11   30      M            2       Y             1   69.50      66.0   
11  12   28      F            1       Y             1   62.75      58.0   
12  13   25      F            1       Y             1   65.00      64.5   

    CWDistance Complete  CompleteGroup  Score  
0           79        Y              1      7  
1           70        Y              1      8  
2           85        Y              1      7  
3           87        Y              1     10  
4           72        N              0      4  
5           81        N              0      3  
6          107        Y              1     10  
7           98        Y              1      9  
8          106        N              0      5  
9           65        Y              1      8  
10          96        Y              1      6  
11          79        Y              1     10  
12          92        Y              1      6

In [67]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [69]:
type(df.columns)

pandas.core.indexes.base.Index

In [70]:
index_list = list(df.columns)

In [71]:
index_list.sort()
index_list

['Age',
 'CWDistance',
 'Complete',
 'CompleteGroup',
 'Gender',
 'GenderGroup',
 'Glasses',
 'GlassesGroup',
 'Height',
 'ID',
 'Score',
 'Wingspan']

In [72]:
for i in df.columns:
    print(i)

ID
Age
Gender
GenderGroup
Glasses
GlassesGroup
Height
Wingspan
CWDistance
Complete
CompleteGroup
Score


In [73]:
df.columns[6]

'Height'

In [79]:
x = df['Height']
print(x)
print(type(x))

0     62.00
1     62.00
2     66.00
3     64.00
4     73.00
5     75.00
6     75.00
7     65.00
8     74.00
9     63.00
10    69.50
11    62.75
12    65.00
13    61.50
14    73.00
15    71.00
16    61.50
17    66.00
18    70.00
19    68.00
20    69.00
21    71.00
22    70.00
23    69.00
24    65.00
Name: Height, dtype: float64
<class 'pandas.core.series.Series'>


In [78]:
y = df[['Height']]
print(y)
print(type(y))

    Height
0    62.00
1    62.00
2    66.00
3    64.00
4    73.00
5    75.00
6    75.00
7    65.00
8    74.00
9    63.00
10   69.50
11   62.75
12   65.00
13   61.50
14   73.00
15   71.00
16   61.50
17   66.00
18   70.00
19   68.00
20   69.00
21   71.00
22   70.00
23   69.00
24   65.00
<class 'pandas.core.frame.DataFrame'>


In [80]:
df[['Age', 'Gender', 'GenderGroup']]

Age Gender  GenderGroup
0    56      F            1
1    26      F            1
2    33      F            1
3    39      F            1
4    27      M            2
5    24      M            2
6    28      M            2
7    22      F            1
8    29      M            2
9    33      F            1
10   30      M            2
11   28      F            1
12   25      F            1
13   23      F            1
14   31      M            2
15   26      M            2
16   26      F            1
17   27      M            2
18   23      M            2
19   24      F            1
20   23      M            2
21   29      M            2
22   25      M            2
23   26      M            2
24   23      F            1

In [85]:
new_df = df.loc[:3,'Height':'Complete'] #rowstart :row end, column_start:column_end, loc con nombre de column
new_df

Height  Wingspan  CWDistance Complete
0    62.0      61.0          79        Y
1    62.0      60.0          70        Y
2    66.0      64.0          85        Y
3    64.0      63.0          87        Y

In [86]:
df.iloc[:3,1:4] #rowstart :row end, column_start:column_end, loc con nombre de column

Age Gender  GenderGroup
0   56      F            1
1   26      F            1
2   33      F            1

In [87]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [88]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [89]:
df.Height.unique()

array([62.  , 66.  , 64.  , 73.  , 75.  , 65.  , 74.  , 63.  , 69.5 ,
       62.75, 61.5 , 71.  , 70.  , 68.  , 69.  ])

In [91]:
df.groupby(['Gender','GenderGroup']).size()

Gender  GenderGroup
F       1              12
M       2              13
dtype: int64